# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mjose <mjose@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/05/26 18:25:27 by mjose             #+#    #+#              #
#    Updated: 2018/10/31 05:53:20 by mjose            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

.PHONY: all, $(NAME), clean, fclean

NAME = minishell

NOC = \033[0m
OKC = \033[32m
ERC = \033[31m
WAC = \033[33m

CLEAR_LINE = \033[2K
BEGIN_LINE = \033[A

CC = gcc
CC_FLAGS = -Wall -Wextra -Werror \
			-g \
			-O1 -g -fsanitize=address	\
			-fno-omit-frame-pointer		\
			-fsanitize-address-use-after-scope \

SRC_PATH = ./sources/
OBJ_PATH = ./objects/
INC_PATH = ./includes/

BUILTINS_PATH = builtins/

B_ENV_PATH = env/
B_CD_PATH = cd/
B_SETENV_PATH = setenv/
B_UNSETENV_PATH = unsetenv/
B_ECHO_PATH = echo/

CORE_PATH = core/
ENV_PATH = environ/
CHKS_PATH = checks/
TOOLS_PATH = tools/
DISP_PATH = display/
COMM_PATH = command/

#		LIBRARY		#

LIB_INC_PATH = ./libft/includes/
LIB_PATH = ./libft/


#		SHELL		#

PATH_SRC_CORE_SHELL = $(SRC_PATH)$(CORE_PATH)
PATH_SRC_CORE_DISP_SHELL = $(PATH_SRC_CORE_SHELL)$(DISP_PATH)
PATH_SRC_CORE_COMM_SHELL = $(PATH_SRC_CORE_SHELL)$(COMM_PATH)
PATH_SRC_CORE_TOOLS_SHELL = $(PATH_SRC_CORE_SHELL)$(TOOLS_PATH)
PATH_SRC_CORE_ENV_SHELL = $(PATH_SRC_CORE_SHELL)$(ENV_PATH)
PATH_SRC_CORE_ENV_CHKS_SHELL = $(PATH_SRC_CORE_ENV_SHELL)$(CHKS_PATH)
PATH_SRC_CORE_ENV_TOOLS_SHELL = $(PATH_SRC_CORE_ENV_SHELL)$(TOOLS_PATH)

PATH_OBJ_CORE_SHELL = $(OBJ_PATH)$(CORE_PATH)
PATH_OBJ_CORE_DISP_SHELL = $(PATH_OBJ_CORE_SHELL)$(DISP_PATH)
PATH_OBJ_CORE_COMM_SHELL = $(PATH_OBJ_CORE_SHELL)$(COMM_PATH)
PATH_OBJ_CORE_TOOLS_SHELL = $(PATH_OBJ_CORE_SHELL)$(TOOLS_PATH)
PATH_OBJ_CORE_ENV_SHELL = $(PATH_OBJ_CORE_SHELL)$(ENV_PATH)
PATH_OBJ_CORE_ENV_CHKS_SHELL = $(PATH_OBJ_CORE_ENV_SHELL)$(CHKS_PATH)
PATH_OBJ_CORE_ENV_TOOLS_SHELL = $(PATH_OBJ_CORE_ENV_SHELL)$(TOOLS_PATH)

#		BUILTINS		#

PATH_SRC_BUILTINS = $(SRC_PATH)$(BUILTINS_PATH)
PATH_SRC_CORE_BUILTINS = $(PATH_SRC_BUILTINS)$(CORE_PATH)

PATH_OBJ_BUILTINS = $(OBJ_PATH)$(BUILTINS_PATH)
PATH_OBJ_CORE_BUILTINS = $(PATH_OBJ_BUILTINS)$(CORE_PATH)

#		BUILTIN ENV		#

PATH_SRC_B_ENV = $(PATH_SRC_BUILTINS)$(B_ENV_PATH)
PATH_SRC_CORE_B_ENV = $(PATH_SRC_B_ENV)$(CORE_PATH)
PATH_SRC_CORE_ENVI_B_ENV = $(PATH_SRC_CORE_B_ENV)$(ENV_PATH)
PATH_SRC_CORE_ENVI_CHKS_B_ENV = $(PATH_SRC_CORE_ENVI_B_ENV)$(CHKS_PATH)
PATH_SRC_CORE_ENVI_TOOLS_B_ENV = $(PATH_SRC_CORE_ENVI_B_ENV)$(TOOLS_PATH)
PATH_SRC_CORE_DISP_B_ENV = $(PATH_SRC_CORE_B_ENV)$(DISP_PATH)

PATH_OBJ_B_ENV = $(PATH_OBJ_BUILTINS)$(B_ENV_PATH)
PATH_OBJ_CORE_B_ENV = $(PATH_OBJ_B_ENV)$(CORE_PATH)
PATH_OBJ_CORE_ENVI_B_ENV = $(PATH_OBJ_CORE_B_ENV)$(ENV_PATH)
PATH_OBJ_CORE_ENVI_CHKS_B_ENV = $(PATH_OBJ_CORE_ENVI_B_ENV)$(CHKS_PATH)
PATH_OBJ_CORE_ENVI_TOOLS_B_ENV = $(PATH_OBJ_CORE_ENVI_B_ENV)$(TOOLS_PATH)
PATH_OBJ_CORE_DISP_B_ENV = $(PATH_OBJ_CORE_B_ENV)$(DISP_PATH)

#		BUILTIN CD		#

PATH_SRC_B_CD = $(PATH_SRC_BUILTINS)$(B_CD_PATH)
PATH_SRC_CORE_B_CD = $(PATH_SRC_B_CD)$(CORE_PATH)
PATH_SRC_CORE_ENVI_B_CD = $(PATH_SRC_CORE_B_CD)$(ENV_PATH)
PATH_SRC_CORE_DISP_B_CD = $(PATH_SRC_CORE_B_CD)$(DISP_PATH)

PATH_OBJ_B_CD = $(PATH_OBJ_BUILTINS)$(B_CD_PATH)
PATH_OBJ_CORE_B_CD = $(PATH_OBJ_B_CD)$(CORE_PATH)
PATH_OBJ_CORE_ENVI_B_CD = $(PATH_OBJ_CORE_B_CD)$(ENV_PATH)
PATH_OBJ_CORE_DISP_B_CD = $(PATH_OBJ_CORE_B_CD)$(DISP_PATH)

#		BUILTIN SETENV		#

PATH_SRC_B_SETENV = $(PATH_SRC_BUILTINS)$(B_SETENV_PATH)
PATH_SRC_CORE_B_SETENV = $(PATH_SRC_B_SETENV)$(CORE_PATH)
PATH_SRC_CORE_DISP_B_SETENV = $(PATH_SRC_CORE_B_SETENV)$(DISP_PATH)
PATH_SRC_CORE_CHKS_B_SETENV = $(PATH_SRC_CORE_B_SETENV)$(CHKS_PATH)
PATH_SRC_CORE_ENVI_B_SETENV = $(PATH_SRC_CORE_B_SETENV)$(ENV_PATH)
PATH_SRC_CORE_ENVI_TOOLS_B_SETENV = $(PATH_SRC_CORE_ENVI_B_SETENV)$(TOOLS_PATH)

PATH_OBJ_B_SETENV = $(PATH_OBJ_BUILTINS)$(B_SETENV_PATH)
PATH_OBJ_CORE_B_SETENV = $(PATH_OBJ_B_SETENV)$(CORE_PATH)
PATH_OBJ_CORE_DISP_B_SETENV = $(PATH_OBJ_CORE_B_SETENV)$(DISP_PATH)
PATH_OBJ_CORE_CHKS_B_SETENV = $(PATH_OBJ_CORE_B_SETENV)$(CHKS_PATH)
PATH_OBJ_CORE_ENVI_B_SETENV = $(PATH_OBJ_CORE_B_SETENV)$(ENV_PATH)
PATH_OBJ_CORE_ENVI_TOOLS_B_SETENV = $(PATH_OBJ_CORE_ENVI_B_SETENV)$(TOOLS_PATH)

#		BUILTIN UNSETENV		#

PATH_SRC_B_UNSETENV = $(PATH_SRC_BUILTINS)$(B_UNSETENV_PATH)
PATH_SRC_CORE_B_UNSETENV = $(PATH_SRC_B_UNSETENV)$(CORE_PATH)
PATH_SRC_CORE_DISP_B_UNSETENV = $(PATH_SRC_CORE_B_UNSETENV)$(DISP_PATH)
PATH_SRC_CORE_ENVI_B_UNSETENV = $(PATH_SRC_CORE_B_UNSETENV)$(ENV_PATH)
PATH_SRC_CORE_ENVI_TOOLS_B_UNSETENV = $(PATH_SRC_CORE_ENVI_B_UNSETENV)$(TOOLS_PATH)

PATH_OBJ_B_UNSETENV = $(PATH_OBJ_BUILTINS)$(B_UNSETENV_PATH)
PATH_OBJ_CORE_B_UNSETENV = $(PATH_OBJ_B_UNSETENV)$(CORE_PATH)
PATH_OBJ_CORE_DISP_B_UNSETENV = $(PATH_OBJ_CORE_B_UNSETENV)$(DISP_PATH)
PATH_OBJ_CORE_ENVI_B_UNSETENV = $(PATH_OBJ_CORE_B_UNSETENV)$(ENV_PATH)
PATH_OBJ_CORE_ENVI_TOOLS_B_UNSETENV = $(PATH_OBJ_CORE_ENVI_B_UNSETENV)$(TOOLS_PATH)

#		BUILTIN ECHO		#

PATH_SRC_B_ECHO = $(PATH_SRC_BUILTINS)$(B_ECHO_PATH)
PATH_SRC_CORE_B_ECHO = $(PATH_SRC_B_ECHO)$(CORE_PATH)
PATH_SRC_CORE_DISP_B_ECHO = $(PATH_SRC_CORE_B_ECHO)$(DISP_PATH)
PATH_SRC_CORE_DISP_CHKS_B_ECHO = $(PATH_SRC_DISP_B_ECHO)$(CHKS_PATH)

PATH_OBJ_B_ECHO = $(PATH_OBJ_BUILTINS)$(B_ECHO_PATH)
PATH_OBJ_CORE_B_ECHO = $(PATH_OBJ_B_ECHO)$(CORE_PATH)
PATH_OBJ_CORE_DISP_B_ECHO = $(PATH_OBJ_CORE_B_ECHO)$(DISP_PATH)
PATH_OBJ_CORE_DISP_CHKS_B_ECHO = $(PATH_OBJ_CORE_DISP_B_ECHO)$(CHKS_PATH)

#		SHELL		#

SRC = $(addprefix $(SRC_PATH),$(SRC_NAME))
SRC_CORE_SHELL = $(addprefix $(PATH_SRC_CORE_SHELL),$(SRC_CORE_SHELL_NAME))
SRC_CORE_DISP_SHELL = $(addprefix $(PATH_SRC_CORE_DISP_SHELL),$(SRC_CORE_DISP_SHELL_NAME))
SRC_CORE_COMM_SHELL = $(addprefix $(PATH_SRC_CORE_COMM_SHELL),$(SRC_CORE_COMM_SHELL_NAME))
SRC_CORE_TOOLS_SHELL = $(addprefix $(PATH_SRC_CORE_TOOLS_SHELL),$(SRC_CORE_TOOLS_SHELL_NAME))
SRC_CORE_ENV_SHELL = $(addprefix $(PATH_SRC_CORE_ENV_SHELL),$(SRC_CORE_ENV_SHELL_NAME))
SRC_CORE_ENV_CHKS_SHELL = $(addprefix $(PATH_SRC_CORE_ENV_CHKS_SHELL),$(SRC_CORE_ENV_CHKS_SHELL_NAME))
SRC_CORE_ENV_TOOLS_SHELL = $(addprefix $(PATH_SRC_CORE_ENV_TOOLS_SHELL),$(SRC_CORE_ENV_TOOLS_SHELL_NAME))

OBJ = $(addprefix $(OBJ_PATH),$(OBJ_NAME))
OBJ_CORE_SHELL = $(addprefix $(PATH_OBJ_CORE_SHELL),$(OBJ_CORE_SHELL_NAME))
OBJ_CORE_DISP_SHELL = $(addprefix $(PATH_OBJ_CORE_DISP_SHELL),$(OBJ_CORE_DISP_SHELL_NAME))
OBJ_CORE_COMM_SHELL = $(addprefix $(PATH_OBJ_CORE_COMM_SHELL),$(OBJ_CORE_COMM_SHELL_NAME))
OBJ_CORE_TOOLS_SHELL = $(addprefix $(PATH_OBJ_CORE_TOOLS_SHELL),$(OBJ_CORE_TOOLS_SHELL_NAME))
OBJ_CORE_ENV_SHELL = $(addprefix $(PATH_OBJ_CORE_ENV_SHELL),$(OBJ_CORE_ENV_SHELL_NAME))
OBJ_CORE_ENV_CHKS_SHELL = $(addprefix $(PATH_OBJ_CORE_ENV_CHKS_SHELL),$(OBJ_CORE_ENV_CHKS_SHELL_NAME))
OBJ_CORE_ENV_TOOLS_SHELL = $(addprefix $(PATH_OBJ_CORE_ENV_TOOLS_SHELL),$(OBJ_CORE_ENV_TOOLS_SHELL_NAME))

INC = $(addprefix $(INC_PATH),$(INC_NAME))

#		BUILTINS		#

SRC_CORE_BUILTINS = $(addprefix $(PATH_SRC_CORE_BUILTINS),$(SRC_CORE_BUILTINS_NAME))

OBJ_CORE_BUILTINS = $(addprefix $(PATH_OBJ_CORE_BUILTINS),$(OBJ_CORE_BUILTINS_NAME))


#		BUILTIN ENV		#

SRC_CORE_B_ENV = $(addprefix $(PATH_SRC_CORE_B_ENV),$(SRC_CORE_B_ENV_NAME))
SRC_CORE_ENVI_B_ENV = $(addprefix $(PATH_SRC_CORE_ENVI_B_ENV),$(SRC_CORE_ENVI_B_ENV_NAME))
SRC_CORE_ENVI_CHKS_B_ENV = $(addprefix $(PATH_SRC_CORE_ENVI_CHKS_B_ENV),$(SRC_CORE_ENVI_B_ENV_NAME))
SRC_CORE_ENVI_TOOLS_B_ENV = $(addprefix $(PATH_SRC_CORE_ENVI_TOOLS_B_ENV),$(SRC_CORE_ENVI_B_ENV_NAME))
SRC_CORE_DISP_B_ENV = $(addprefix $(PATH_SRC_CORE_DISP_B_ENV),$(SRC_CORE_DISP_B_ENV_NAME))

OBJ_CORE_B_ENV = $(addprefix $(PATH_OBJ_CORE_B_ENV),$(OBJ_CORE_B_ENV_NAME))
OBJ_CORE_ENVI_B_ENV = $(addprefix $(PATH_OBJ_CORE_ENVI_B_ENV),$(OBJ_CORE_ENVI_B_ENV_NAME))
OBJ_CORE_ENVI_CHKS_B_ENV = $(addprefix $(PATH_OBJ_CORE_ENVI_CHKS_B_ENV),$(OBJ_CORE_ENVI_CHKS_B_ENV_NAME))
OBJ_CORE_ENVI_TOOLS_B_ENV = $(addprefix $(PATH_OBJ_CORE_ENVI_TOOLS_B_ENV),$(OBJ_CORE_ENVI_TOOLS_B_ENV_NAME))
OBJ_CORE_DISP_B_ENV = $(addprefix $(PATH_OBJ_CORE_DISP_B_ENV),$(OBJ_CORE_DISP_B_ENV_NAME))

#		BUILTIN CD		#

SRC_CORE_B_CD = $(addprefix $(PATH_SRC_CORE_B_CD),$(SRC_CORE_B_CD_NAME))
SRC_CORE_ENVI_B_CD = $(addprefix $(PATH_SRC_CORE_ENVI_B_CD),$(SRC_CORE_ENVI_B_CD_NAME))
SRC_CORE_DISP_B_CD = $(addprefix $(PATH_SRC_CORE_DISP_B_CD),$(SRC_CORE_DISP_B_CD_NAME))

OBJ_CORE_B_CD = $(addprefix $(PATH_OBJ_CORE_B_CD),$(OBJ_CORE_B_CD_NAME))
OBJ_CORE_ENVI_B_CD = $(addprefix $(PATH_OBJ_CORE_ENVI_B_CD),$(OBJ_CORE_ENVI_B_CD_NAME))
OBJ_CORE_DISP_B_CD = $(addprefix $(PATH_OBJ_CORE_DISP_B_CD),$(OBJ_CORE_DISP_B_CD_NAME))

#		BUILTIN SETENV		#

SRC_CORE_B_SETENV = $(addprefix $(PATH_SRC_CORE_B_SETENV),$(SRC_CORE_B_SETENV_NAME))
SRC_CORE_DISP_B_SETENV = $(addprefix $(PATH_SRC_CORE_DISP_B_SETENV),$(SRC_CORE_DISP_B_SETENV_NAME))
SRC_CORE_CHKS_B_SETENV = $(addprefix $(PATH_SRC_CORE_CHKS_B_SETENV),$(SRC_CORE_CHKS_B_SETENV_NAME))
SRC_CORE_ENVI_B_SETENV = $(addprefix $(PATH_SRC_CORE_ENVI_B_SETENV),$(SRC_CORE_ENVI_B_SETENV_NAME))
SRC_CORE_ENVI_TOOLS_B_SETENV = $(addprefix $(PATH_SRC_CORE_ENVI_TOOLS_B_SETENV),$(SRC_CORE_ENVI_TOOLS_B_SETENV_NAME))

OBJ_CORE_B_SETENV = $(addprefix $(PATH_OBJ_CORE_B_SETENV),$(OBJ_CORE_B_SETENV_NAME))
OBJ_CORE_DISP_B_SETENV = $(addprefix $(PATH_OBJ_CORE_DISP_B_SETENV),$(OBJ_CORE_DISP_B_SETENV_NAME))
OBJ_CORE_CHKS_B_SETENV = $(addprefix $(PATH_OBJ_CORE_CHKS_B_SETENV),$(OBJ_CORE_CHKS_B_SETENV_NAME))
OBJ_CORE_ENVI_B_SETENV = $(addprefix $(PATH_OBJ_CORE_ENVI_B_SETENV),$(OBJ_CORE_ENVI_B_SETENV_NAME))
OBJ_CORE_ENVI_TOOLS_B_SETENV = $(addprefix $(PATH_OBJ_CORE_ENVI_TOOLS_B_SETENV),$(OBJ_CORE_ENVI_TOOLS_B_SETENV_NAME))

#		BUILTIN UNSETENV		#

SRC_CORE_B_UNSETENV = $(addprefix $(PATH_SRC_CORE_B_UNSETENV),$(SRC_CORE_B_UNSETENV_NAME))
SRC_CORE_DISP_B_UNSETENV = $(addprefix $(PATH_SRC_CORE_DISP_B_UNSETENV),$(SRC_CORE_DISP_B_UNSETENV_NAME))
SRC_CORE_ENVI_B_UNSETENV = $(addprefix $(PATH_SRC_CORE_ENVI_B_UNSETENV),$(SRC_CORE_ENVI_B_UNSETENV_NAME))
SRC_CORE_ENVI_TOOLS_B_UNSETENV = $(addprefix $(PATH_SRC_CORE_ENVI_TOOLS_B_UNSETENV),$(SRC_CORE_ENVI_TOOLS_B_UNSETENV_NAME))

OBJ_CORE_B_UNSETENV = $(addprefix $(PATH_OBJ_CORE_B_UNSETENV),$(OBJ_CORE_B_UNSETENV_NAME))
OBJ_CORE_DISP_B_UNSETENV = $(addprefix $(PATH_OBJ_CORE_DISP_B_UNSETENV),$(OBJ_CORE_DISP_B_UNSETENV_NAME))
OBJ_CORE_ENVI_B_UNSETENV = $(addprefix $(PATH_OBJ_CORE_ENVI_B_UNSETENV),$(OBJ_CORE_ENVI_B_UNSETENV_NAME))
OBJ_CORE_ENVI_TOOLS_B_UNSETENV = $(addprefix $(PATH_OBJ_CORE_ENVI_TOOLS_B_UNSETENV),$(OBJ_CORE_ENVI_TOOLS_B_UNSETENV_NAME))

#		BUILTIN ECHO		#

SRC_CORE_B_ECHO = $(addprefix $(PATH_SRC_CORE_B_ECHO),$(SRC_CORE_B_ECHO_NAME))
SRC_CORE_DISP_B_ECHO = $(addprefix $(PATH_SRC_CORE_DISP_B_ECHO),$(SRC_CORE_DISP_B_ECHO_NAME))
SRC_CORE_DISP_CHKS_B_ECHO = $(addprefix $(PATH_SRC_CORE_DISP_CHKS_B_ECHO),$(SRC_CORE_DISP_CHKS_B_ECHO_NAME))

OBJ_CORE_B_ECHO = $(addprefix $(PATH_OBJ_CORE_B_ECHO),$(OBJ_CORE_B_ECHO_NAME))
OBJ_CORE_DISP_B_ECHO = $(addprefix $(PATH_OBJ_CORE_DISP_B_ECHO),$(OBJ_CORE_DISP_B_ECHO_NAME))
OBJ_CORE_DISP_CHKS_B_ECHO = $(addprefix $(PATH_OBJ_CORE_DISP_CHKS_B_ECHO),$(OBJ_CORE_DISP_CHKS_B_ECHO_NAME))

#		SHELL		#

OBJ_NAME = $(SRC_NAME:.c=.o)
OBJ_CORE_SHELL_NAME = $(SRC_CORE_SHELL_NAME:.c=.o)
OBJ_CORE_DISP_SHELL_NAME = $(SRC_CORE_DISP_SHELL_NAME:.c=.o)
OBJ_CORE_COMM_SHELL_NAME = $(SRC_CORE_COMM_SHELL_NAME:.c=.o)
OBJ_CORE_TOOLS_SHELL_NAME = $(SRC_CORE_TOOLS_SHELL_NAME:.c=.o)
OBJ_CORE_ENV_SHELL_NAME = $(SRC_CORE_ENV_SHELL_NAME:.c=.o)
OBJ_CORE_ENV_CHKS_SHELL_NAME = $(SRC_CORE_ENV_CHKS_SHELL_NAME:.c=.o)
OBJ_CORE_ENV_TOOLS_SHELL_NAME = $(SRC_CORE_ENV_TOOLS_SHELL_NAME:.c=.o)

#		BUILTINS		#

OBJ_CORE_BUILTINS_NAME = $(SRC_CORE_BUILTINS_NAME:.c=.o)

#		BUILTIN ENV		#

OBJ_CORE_B_ENV_NAME = $(SRC_CORE_B_ENV_NAME:.c=.o)
OBJ_CORE_ENVI_B_ENV_NAME = $(SRC_CORE_ENVI_B_ENV_NAME:.c=.o)
OBJ_CORE_ENVI_CHKS_B_ENV_NAME = $(SRC_CORE_ENVI_CHKS_B_ENV_NAME:.c=.o)
OBJ_CORE_ENVI_TOOLS_B_ENV_NAME = $(SRC_CORE_ENVI_TOOLS_B_ENV_NAME:.c=.o)
OBJ_CORE_DISP_B_ENV_NAME = $(SRC_CORE_DISP_B_ENV_NAME:.c=.o)

#		BUILTIN CD		#

OBJ_CORE_B_CD_NAME = $(SRC_CORE_B_CD_NAME:.c=.o)
OBJ_CORE_ENVI_B_CD_NAME = $(SRC_CORE_ENVI_B_CD_NAME:.c=.o)
OBJ_CORE_DISP_B_CD_NAME = $(SRC_CORE_DISP_B_CD_NAME:.c=.o)

#		BUILTIN SETENV		#

OBJ_CORE_B_SETENV_NAME = $(SRC_CORE_B_SETENV_NAME:.c=.o)
OBJ_CORE_DISP_B_SETENV_NAME = $(SRC_CORE_DISP_B_SETENV_NAME:.c=.o)
OBJ_CORE_CHKS_B_SETENV_NAME = $(SRC_CORE_CHKS_B_SETENV_NAME:.c=.o)
OBJ_CORE_ENVI_B_SETENV_NAME = $(SRC_CORE_ENVI_B_SETENV_NAME:.c=.o)
OBJ_CORE_ENVI_TOOLS_B_SETENV_NAME = $(SRC_CORE_ENVI_TOOLS_B_SETENV_NAME:.c=.o)

#		BUILTIN UNSETENV		#

OBJ_CORE_B_UNSETENV_NAME = $(SRC_CORE_B_UNSETENV_NAME:.c=.o)
OBJ_CORE_DISP_B_UNSETENV_NAME = $(SRC_CORE_DISP_B_UNSETENV_NAME:.c=.o)
OBJ_CORE_ENVI_B_UNSETENV_NAME = $(SRC_CORE_ENVI_B_UNSETENV_NAME:.c=.o)
OBJ_CORE_ENVI_TOOLS_B_UNSETENV_NAME = $(SRC_CORE_ENVI_TOOLS_B_UNSETENV_NAME:.c=.o)

#		BUILTIN ECHO		#

OBJ_CORE_B_ECHO_NAME = $(SRC_CORE_B_ECHO_NAME:.c=.o)
OBJ_CORE_DISP_B_ECHO_NAME = $(SRC_CORE_DISP_B_ECHO_NAME:.c=.o)
OBJ_CORE_DISP_CHKS_B_ECHO_NAME = $(SRC_CORE_DISP_CHKS_B_ECHO_NAME:.c=.o)

#		SHELL		#

INC_NAME = minishell.h

SRC_NAME = 
SRC_CORE_SHELL_NAME = main.c exec.c
SRC_CORE_DISP_SHELL_NAME = prompt.c error.c 
SRC_CORE_COMM_SHELL_NAME = command.c com_str.c com_tab.c init_split.c com_tab_arg.c \
							com_tab_arg_crt.c types.c tol_tab_arg.c tol_tab_arg_crt.c
SRC_CORE_TOOLS_SHELL_NAME = shell.c checks.c
SRC_CORE_ENV_SHELL_NAME = environ.c path.c
SRC_CORE_ENV_CHKS_SHELL_NAME = chk_home_oldpwd.c
SRC_CORE_ENV_TOOLS_SHELL_NAME = sets.c searches.c

#		BUILTINS		#

SRC_CORE_BUILTINS_NAME = exec.c

#		BUILTIN ENV		#

SRC_CORE_B_ENV_NAME = exec.c init.c
SRC_CORE_ENVI_B_ENV_NAME = environ_tmp.c
SRC_CORE_DISP_B_ENV_NAME = error.c display.c
SRC_CORE_ENVI_CHKS_B_ENV_NAME = checks.c
SRC_CORE_ENVI_TOOLS_B_ENV_NAME = sets.c sets_without_env.c searches.c

#		BUILTIN CD		#

SRC_CORE_B_CD_NAME = exec.c chg_dir.c chg_dir_with_return.c
SRC_CORE_DISP_B_CD_NAME = error.c error_arg.c display.c

#		BUILTIN SETENV		#

SRC_CORE_B_SETENV_NAME = exec.c
SRC_CORE_DISP_B_SETENV_NAME = error.c display.c
SRC_CORE_CHKS_B_SETENV_NAME = var_name.c
SRC_CORE_ENVI_TOOLS_B_SETENV_NAME = create.c sets.c sets_sysvar.c searches.c

#		BUILTIN UNSETENV		#

SRC_CORE_B_UNSETENV_NAME = exec.c
SRC_CORE_DISP_B_UNSETENV_NAME = error.c
SRC_CORE_ENVI_TOOLS_B_UNSETENV_NAME = unsets.c

#		BUILTIN ECHO		#

SRC_CORE_B_ECHO_NAME = exec.c
SRC_CORE_DISP_B_ECHO_NAME = display.c
SRC_CORE_DISP_CHKS_B_ECHO_NAME =

all: $(NAME)

$(NAME): lib core b_ENV b_CD b_SETENV b_UNSETENV b_ECHO b_core $(OBJ)
	@$(CC) -o $(NAME) \
	$(OBJ) \
	$(OBJ_CORE_SHELL) \
	$(OBJ_CORE_ENV_CHKS_SHELL) \
	$(OBJ_CORE_ENV_TOOLS_SHELL) \
	$(OBJ_CORE_ENV_SHELL) \
	$(OBJ_CORE_COMM_SHELL) \
	$(OBJ_CORE_DISP_SHELL) \
	$(OBJ_CORE_TOOLS_SHELL) \
	$(OBJ_CORE_BUILTINS) \
	$(OBJ_CORE_ENVI_CHKS_B_ENV) \
	$(OBJ_CORE_ENVI_TOOLS_B_ENV) \
	$(OBJ_CORE_ENVI_B_ENV) \
	$(OBJ_CORE_DISP_B_ENV) \
	$(OBJ_CORE_B_ENV) \
	$(OBJ_CORE_DISP_B_CD) \
	$(OBJ_CORE_B_CD) \
	$(OBJ_CORE_DISP_B_SETENV) \
	$(OBJ_CORE_CHKS_B_SETENV) \
	$(OBJ_CORE_ENVI_TOOLS_B_SETENV) \
	$(OBJ_CORE_B_SETENV) \
	$(OBJ_CORE_DISP_B_UNSETENV) \
	$(OBJ_CORE_ENVI_TOOLS_B_UNSETENV) \
	$(OBJ_CORE_B_UNSETENV) \
	$(OBJ_CORE_DISP_CHKS_B_ECHO) \
	$(OBJ_CORE_DISP_B_ECHO) \
	$(OBJ_CORE_B_ECHO) \
	$(CC_FLAGS) -L $(LIB_PATH) -lft
	@echo "$(WAC)MINISHELL STATUS:\t\t$(OKC)Ready$(NOC)"
	@echo ===============MINISHELL===============
lib:
	@make -C $(LIB_PATH)
	@echo ===============MINISHELL===============

#		SHELL		#

core_env_tools: $(OBJ_CORE_ENV_TOOLS_SHELL)
	
$(PATH_OBJ_CORE_ENV_TOOLS_SHELL)%.o: $(PATH_SRC_CORE_ENV_TOOLS_SHELL)%.c)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

core_env_chks: $(OBJ_CORE_ENV_CHKS_SHELL)
	
$(PATH_OBJ_CORE_ENV_CHKS_SHELL)%.o: $(PATH_SRC_CORE_ENV_CHKS_SHELL)%.c)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

core_env: $(OBJ_CORE_ENV_SHELL)
	@echo "$(CLEAR_LINE)$(WAC)MINISHELL ENVIRONMENT:\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_ENV_SHELL)%.o: $(PATH_SRC_CORE_ENV_SHELL)%.c
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@mkdir -p $(PATH_OBJ_CORE_ENV_SHELL)
	@mkdir -p $(PATH_OBJ_CORE_ENV_CHKS_SHELL)
	@mkdir -p $(PATH_OBJ_CORE_ENV_TOOLS_SHELL)
	@$(CC)  -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

core_disp: $(OBJ_CORE_DISP_SHELL)
	@echo "$(CLEAR_LINE)$(WAC)MINISHELL DISPLAY:\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_DISP_SHELL)%.o: $(PATH_SRC_CORE_DISP_SHELL)%.c
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@mkdir -p $(PATH_OBJ_CORE_DISP_SHELL)
	@$(CC)  -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

core_comm: $(OBJ_CORE_COMM_SHELL)
	@echo "$(CLEAR_LINE)$(WAC)MINISHELL COMMAND:\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_COMM_SHELL)%.o: $(PATH_SRC_CORE_COMM_SHELL)%.c
	@echo "$(CLEAR_LINE)$(WAC)COMMAND BINARIES:\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@mkdir -p $(PATH_OBJ_CORE_COMM_SHELL)
	@$(CC)  -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

core_tools: $(OBJ_CORE_TOOLS_SHELL)

$(PATH_OBJ_CORE_TOOLS_SHELL)%.o: $(PATH_SRC_CORE_TOOLS_SHELL)%.c
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@mkdir -p $(PATH_OBJ_CORE_TOOLS_SHELL)
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)TOOLS BINARIES:\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

core: $(OBJ_CORE_SHELL) core_env_tools core_env_chks core_env core_disp core_tools \
	core_comm
	@echo "$(CLEAR_LINE)$(WAC)MINISHELL CORE:\t\t\t$(OKC)Ready$(NOC)"
	@echo ===============BUILTINS================

$(PATH_OBJ_CORE_SHELL)%.o: $(PATH_SRC_CORE_SHELL)%.c
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@mkdir -p $(PATH_OBJ_CORE_SHELL)
	@$(CC)  -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

#		BUILTINS		#

b_core: $(OBJ_CORE_BUILTINS)
	@echo "$(CLEAR_LINE)$(WAC)BUILTINS CORE:\t\t\t$(OKC)Ready$(NOC)"
	@echo ---------------------------------------
	@echo "$(WAC)BUILTINS STATUS:\t\t$(OKC)Ready$(NOC)"
	@echo ===============BUILTINS================

$(PATH_OBJ_CORE_BUILTINS)%.o: $(PATH_SRC_CORE_BUILTINS)%.c
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@mkdir -p $(PATH_OBJ_CORE_BUILTINS)
	@$(CC)  -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

#		BUILTIN ENV		#

b_ENV_core_envi_chks: $(OBJ_CORE_ENVI_CHKS_B_ENV)
	
$(PATH_OBJ_CORE_ENVI_CHKS_B_ENV)%.o: $(PATH_SRC_CORE_ENVI_CHKS_B_ENV)%.c)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_ENV_core_envi_tools: $(OBJ_CORE_ENVI_TOOLS_B_ENV)
	
$(PATH_OBJ_CORE_ENVI_TOOLS_B_ENV)%.o: $(PATH_SRC_CORE_ENVI_TOOLS_B_ENV)%.c)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_ENV_core_envi: $(OBJ_CORE_ENVI_B_ENV)
	@echo "$(CLEAR_LINE)$(WAC)ENV ENVIRONMENT:\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_ENVI_B_ENV)%.o: $(PATH_SRC_CORE_ENVI_B_ENV)%.c)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_ENV_core_disp: $(OBJ_CORE_DISP_B_ENV)
	@echo "$(CLEAR_LINE)$(WAC)ENV DISPLAY:\t\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_DISP_B_ENV)%.o: $(PATH_SRC_CORE_DISP_B_ENV)%.c)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_ENV_core: $(OBJ_CORE_B_ENV)
	@echo "$(CLEAR_LINE)$(WAC)ENV CORE:\t\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_B_ENV)%.o: $(PATH_SRC_CORE_B_ENV)%.c
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@mkdir -p $(PATH_OBJ_CORE_B_ENV)
	@mkdir -p $(PATH_OBJ_CORE_DISP_B_ENV)
	@mkdir -p $(PATH_OBJ_CORE_ENVI_B_ENV)
	@mkdir -p $(PATH_OBJ_CORE_ENVI_CHKS_B_ENV)
	@mkdir -p $(PATH_OBJ_CORE_ENVI_TOOLS_B_ENV)
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

#		BUILTIN CD		#

b_CD_core_disp: $(OBJ_CORE_DISP_B_CD)
	@echo "$(CLEAR_LINE)$(WAC)CD DISPLAY:\t\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_DISP_B_CD)%.o: $(PATH_SRC_CORE_DISP_B_CD)%.c)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_CD_core: $(OBJ_CORE_B_CD)
	@echo "$(CLEAR_LINE)$(WAC)CD CORE:\t\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_B_CD)%.o: $(PATH_SRC_CORE_B_CD)%.c
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@mkdir -p $(PATH_OBJ_CORE_B_CD)
	@mkdir -p $(PATH_OBJ_CORE_DISP_B_CD)
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

#		BUILTIN SETENV		#

b_SETENV_core_envi_tools: $(OBJ_CORE_ENVI_TOOLS_B_SETENV)
	
$(PATH_OBJ_CORE_ENVI_TOOLS_B_SETENV)%.o: $(PATH_SRC_CORE_ENVI_TOOLS_B_SETENV)%.c)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_SETENV_core_envi: b_SETENV_core_envi_tools
	@echo "$(CLEAR_LINE)$(WAC)SETENV ENVIRONMENT:\t\t$(OKC)Ready$(NOC)"

b_SETENV_core_chks: $(OBJ_CORE_CHKS_B_SETENV)

$(PATH_OBJ_CORE_CHKS_B_SETENV)%.o: $(PATH_SRC_CORE_CHKS_B_SETENV)%.c)
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $<$(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_SETENV_core_disp: $(OBJ_CORE_DISP_B_SETENV)
	@echo "$(CLEAR_LINE)$(WAC)SETENV DISPLAY:\t\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_DISP_B_SETENV)%.o: $(PATH_SRC_CORE_DISP_B_SETENV)%.c)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_SETENV_core: $(OBJ_CORE_B_SETENV)
	@echo "$(CLEAR_LINE)$(WAC)SETENV CORE:\t\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_B_SETENV)%.o: $(PATH_SRC_CORE_B_SETENV)%.c
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@mkdir -p $(PATH_OBJ_CORE_B_SETENV)
	@mkdir -p $(PATH_OBJ_CORE_DISP_B_SETENV)
	@mkdir -p $(PATH_OBJ_CORE_CHKS_B_SETENV)
	@mkdir -p $(PATH_OBJ_CORE_ENVI_B_SETENV)
	@mkdir -p $(PATH_OBJ_CORE_ENVI_TOOLS_B_SETENV)
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

#		BUILTIN UNSETENV		#

b_UNSETENV_core_envi_tools: $(OBJ_CORE_ENVI_TOOLS_B_UNSETENV)
	
$(PATH_OBJ_CORE_ENVI_TOOLS_B_UNSETENV)%.o: $(PATH_SRC_CORE_ENVI_TOOLS_B_UNSETENV)%.c)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)ENVIRONMENT BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_UNSETENV_core_envi: b_UNSETENV_core_envi_tools
	@echo "$(CLEAR_LINE)$(WAC)UNSETENV ENVIRONMENT:\t\t$(OKC)Ready$(NOC)"

b_UNSETENV_core_disp: $(OBJ_CORE_DISP_B_UNSETENV)
	@echo "$(CLEAR_LINE)$(WAC)UNSETENV DISPLAY:\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_DISP_B_UNSETENV)%.o: $(PATH_SRC_CORE_DISP_B_UNSETENV)%.c)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_UNSETENV_core: $(OBJ_CORE_B_UNSETENV)
	@echo "$(CLEAR_LINE)$(WAC)UNSETENV CORE:\t\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_B_UNSETENV)%.o: $(PATH_SRC_CORE_B_UNSETENV)%.c
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@mkdir -p $(PATH_OBJ_CORE_B_UNSETENV)
	@mkdir -p $(PATH_OBJ_CORE_DISP_B_UNSETENV)
	@mkdir -p $(PATH_OBJ_CORE_ENVI_B_UNSETENV)
	@mkdir -p $(PATH_OBJ_CORE_ENVI_TOOLS_B_UNSETENV)
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

#		BUILTIN ECHO		#

b_ECHO_core_disp_chks: $(OBJ_CORE_DISP_CHKS_B_ECHO)
	
$(PATH_OBJ_CORE_DISP_CHKS_B_ECHO)%.o: $(PATH_SRC_CORE_DISP_CHKS_B_ECHO)%.c)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_ECHO_core_disp: $(OBJ_CORE_DISP_B_ECHO)
	@echo "$(CLEAR_LINE)$(WAC)ECHO DISPLAY:\t\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_DISP_B_ECHO)%.o: $(PATH_SRC_CORE_DISP_B_ECHO)%.c)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)DISPLAY BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

b_ECHO_core: $(OBJ_CORE_B_ECHO)
	@echo "$(CLEAR_LINE)$(WAC)ECHO CORE:\t\t\t$(OKC)Ready$(NOC)"

$(PATH_OBJ_CORE_B_ECHO)%.o: $(PATH_SRC_CORE_B_ECHO)%.c
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(NOC)Making binary...\t$(OKC)$@$(NOC)$(BEGIN_LINE)"
	@mkdir -p $(PATH_OBJ_CORE_B_ECHO)
	@mkdir -p $(PATH_OBJ_CORE_DISP_B_ECHO)
	@mkdir -p $(PATH_OBJ_CORE_DISP_CHKS_B_ECHO)
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)
	@echo "$(CLEAR_LINE)$(WAC)CORE BINARIES:\t\t\t$(OKC)Ready$(NOC)$(BEGIN_LINE)"

#		BUILTIN STATUS		#

b_ENV: b_ENV_core_envi_chks b_ENV_core_envi_tools b_ENV_core_envi b_ENV_core_disp b_ENV_core
	@echo ---------------------------------------
	@echo "$(CLEAR_LINE)$(WAC)BUILTIN ENV STATUS:\t\t$(OKC)Ready$(NOC)"
	@echo ---------------------------------------

b_CD: b_CD_core_disp b_CD_core 
	@echo ---------------------------------------
	@echo "$(CLEAR_LINE)$(WAC)BUILTIN CD STATUS:\t\t$(OKC)Ready$(NOC)"
	@echo ---------------------------------------

b_SETENV: b_SETENV_core_envi_tools b_SETENV_core_envi b_SETENV_core_chks b_SETENV_core_disp b_SETENV_core
	@echo ---------------------------------------
	@echo "$(CLEAR_LINE)$(WAC)BUILTIN SETENV STATUS:\t\t$(OKC)Ready$(NOC)"
	@echo ---------------------------------------

b_UNSETENV: b_UNSETENV_core_envi_tools b_UNSETENV_core_envi b_UNSETENV_core_disp b_UNSETENV_core
	@echo ---------------------------------------
	@echo "$(CLEAR_LINE)$(WAC)BUILTIN UNSETENV STATUS:\t$(OKC)Ready$(NOC)"
	@echo ---------------------------------------

b_ECHO: b_ECHO_core_disp_chks b_ECHO_core_disp b_ECHO_core
	@echo ---------------------------------------
	@echo "$(CLEAR_LINE)$(WAC)BUILTIN ECHO STATUS:\t\t$(OKC)Ready$(NOC)"
	@echo ---------------------------------------

$(OBJ_PATH)%.o: $(SRC_PATH)%.c
	@mkdir -p $(OBJ_PATH)
	@$(CC) -o $@ -c $< $(CC_FLAGS) -I $(INC_PATH) -I $(LIB_INC_PATH)

clean:
	@rm -rf $(OBJ_PATH)
	@echo "$(WAC)MINISHELL:\t\t\t$(ERC)Binaries folder removed.$(NOC)"

fclean: clean
	@make -C $(LIB_PATH) fclean
	@rm -rf $(NAME)
	@echo "$(WAC)MINISHELL:\t\t\t$(ERC)Executable removed.$(NOC)"

re: fclean all
